# Generated by Django 4.1.1 on 2022-11-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Employeee_fname', models.CharField(max_length=150)),
                ('Employeee_lname', models.CharField(max_length=150)),
                ('Employeee_mail_id', models.CharField(max_length=150)),
            ],
        ),
    ]
